# Generated by Django 5.0.1 on 2024-04-15 12:57

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_roomconnecteduser'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='roomconnecteduser',
            unique_together={('chatroom', 'user')},
        ),
    ]
